### ISSUE TITLE
Implement AI explanations using Samba Nova

### ISSUE THREAD

**Issue by sohalsdr** [pufferfish-app/api#2]
Create an endpoint that, based on a possible fraudulent transaction record, generates and returns a short AI-generated summary of what the potential fraud is, why it matters, and what a user can do to resolve the situation.

**Comment by DaraMoh** [comment]
Currently provides a short AI-generated summary that says what the potential fraud is. Does not:
- say why it matters
- say what a user can do to resolve the situation
