### ISSUE TITLE
Implement fraudulent transaction detection

### ISSUE THREAD

**Issue by sohalsdr** [pufferfish-app/api#3]
Create an endpoint that, based on a user's transaction data pulled from SimpleFIN, checks for different kinds of fraudulent transactions and creates a list of possible fraudulent transaction records in a standardized format.

**Comment by DaraMoh** [comment]
Fraudulent Transactions implemented fully:
- P2P Payment
- Popular Scam Locations

Fraudulent Transactions not fully implemented:
- late transactions
